routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/topics', TopicController::class);
Route::resource('/content', ContentController::class);

Route::get('logout', function(){
    auth()->logout();
    return redirect('login');
});

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card mb-3 mr-3" style="width: 16rem; ">
                <a href="{{ route('content.create') }}" class="btn"><i class="fa fa-plus-circle fa-6x" style="color: black" ></i>
                   <h4 class="card-body" style="color: black">Add Content</h4>
                </a>
            </div>
            <div class="card  mb-3 mr-3" style="width: 16rem;">
                <a href="{{ URL::to('/content') }}" class="btn"><i class="fa fa-camera fa-6x" style="color: black"></i>
                    <h4 class="card-body" style="color: black">Available Content</h4>
                </a>
            </div>
            <div class="card mb-3 mr-3" style="width: 16rem;">
                <a href="{{ route('topics.create') }}" class="btn"><i class="fa fa-plus-circle fa-6x" style="color: black"></i>
                    <h4 class="card-body" style="color: black">Add Topic</h4>
                </a>
            </div>
            <div class="card mb-3 mr-3" style="width: 16rem;">
                <a href="{{ route('topics.index') }}" class="btn"><i class="fa fa-book fa-6x" style="color: black"></i>
                    <h4 class="card-body" style="color: black">Available Topics</h4>
                </a>
            </div>
        </div>
@endsection