routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/topics', TopicController::class);
Route::resource('/content', ContentController::class);

Route::get('logout', function(){
    auth()->logout();
    return redirect('login');
});

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    use HasFactory;

    protected $guarded = ['id', 'created_at'];

    function content()
    {
        return $this->hasMany(Content::class, 'topic_id', 'id');
    }
}

app/Http/Controllers/API/TopicController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::with('content')->inRandomOrder()->paginate(1000);

        return response()->json($topics);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $topic = Topic::find($id);
        if (!$topic) {
            return response()->json([
                'status' => 'FAILED'
            ]);
        }
        return response()->json($topic);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\lead;
use App\Models\Topic;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::paginate();
        return view('topics.index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'  => 'required',
            'media' => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        $lead = Topic::create([
            'media'   => $request->media,
            'name'    => 'Topic'. $request->name,
            'user_id' => Auth::user()->id,
        ]);

        return redirect()->route('topics.index')->with('message', 'Topic created successfully !');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        return view('topics.view',compact('topic'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        return view('topics.edit',compact('topic'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Topic $topic)
    {
        $validator = Validator::make($request->all(), [
            'name'    => 'required',
            'media'   => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        $topic->update($request->all());

        return redirect()->route('topics.index')->with('message','Topic updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
//        return $topic;
//        return view('topics.delete',compact('topic'));
    }
}

resources/views/topics/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-6 col-md-offset-1">

                <h4 class="mb-4">New topic</h4>

                <form method="POST" action="{{{ URL::to('/topics') }}}" accept-charset="UTF-8">
                    {{ csrf_field() }}

                    <div class="mb-3">
                        <label  class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" value="{{ old('name') }}" >
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="form-label">Add media</label>
                            <input type="file" name="media" class="form-control-file">
                            @error('media')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Create topic</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/topics/destroy.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-6 col-md-offset-1">

                <h4 class="mb-4">New topic</h4>

                <div class="row">
                    <div class="col-4 mb-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ $topic->media }}">
                            <div class="card-body p-2">
                                <p class="card-text text-justify">
                                    {{ $topic->name }}
                                </p>

                            </div>
                            <div class="text-center">
                            </div>
                        </div>
                        <button class="btn-group btn-group-sm">
                            <a href="#" class="btn btn-danger btn-sm">Delete Topic</a>
                        </button>
                        <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger"  onclick="return confirm('Are you sure you want to delete this sales lead ?')">Delete topic</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/topics/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-6 col-md-offset-1">

                <h4 class="mb-4">New topic</h4>

                    <form method="POST" action="{{{ URL::to('topics/'.$topic->id) }}}" accept-charset="UTF-8" >
                        @method('PUT')
                        {{ csrf_field() }}

                    <div class="mb-3">
                        <label  class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" value="{{ $topic->name}}" >
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="form-label">Add media</label>
                            <input type="file" name="media" value="{{ $topic->media}}" class="form-control-file">
                            @error('media')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Update topic</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/topics/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-12 col-md-offset-1">

                <a href="{{ route('topics.create') }}" type="button" class="btn btn-success ml-auto float-right">
                    Create Topic
                </a>
                <h3 class="mb-4">List of Topics</h3>

                <table class="table table-bordered table-sm">
                    @foreach($topics as $topic)
                        <tr>
                            <td class="pl-3">{{$topic->name}}</td>
                            <td>
                                <a href="{{ route('topics.destroy', ['topic' => $topic->id]) }}"
                                   class="btn btn-outline-danger btn-sm float-right">Delete</a>
                                <a href="{{ route('topics.show', ['topic' => $topic->id]) }}"
                                   class="btn btn-outline-info btn-sm float-right mr-2">View</a>
                                <a href="{{ route('topics.edit', ['topic' => $topic->id]) }}"
                                class="btn btn-outline-primary btn-sm float-right mr-2">Edit</a>
                            </td>
                        </tr>
                    @endforeach
                </table>

                <div>
                    {{ $topics->links() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-10 col-md-offset-1">

                <h4 class="mb-4">{{ $topic->name }}</h4>

                <div class="row">
                    <div class="col-8 mb-6">
                        <div class="card">
                            <img class="card-img-top" src="{{ $topic->media }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection